/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.fluss.lake.paimon.utils;

import org.apache.fluss.exception.TableAlreadyExistException;
import org.apache.fluss.metadata.TablePath;

import org.apache.paimon.CoreOptions;
import org.apache.paimon.schema.Schema;
import org.apache.paimon.table.FileStoreTable;
import org.apache.paimon.types.DataField;
import org.apache.paimon.types.DataTypes;
import org.apache.paimon.types.RowType;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import static org.apache.fluss.lake.paimon.utils.PaimonConversions.PAIMON_UNSETTABLE_OPTIONS;
import static org.apache.fluss.lake.paimon.utils.PaimonConversions.PARTITION_GENERATE_LEGACY_NAME_OPTION_KEY;
import static org.apache.fluss.metadata.TableDescriptor.TIMESTAMP_COLUMN_NAME;

/** Utils to verify whether the existing Paimon table is compatible with the table to be created. */
public class PaimonTableValidation {

    public static boolean isPaimonSchemaCompatible(Schema existingSchema, Schema newSchema) {
        if (!equalPhysicalSchema(existingSchema, newSchema)) {
            // Allow different precisions for __timestamp column for backward compatibility,
            // old cluster will use precision 6, but new cluster will use precision 3,
            // we allow such precision difference
            return equalIgnoreSystemColumnTimestampPrecision(existingSchema, newSchema);
        }

        return true;
    }

    /**
     * Check if the {@code existingSchema} is compatible with {@code newSchema} by ignoring the
     * precision difference of the system column {@code __timestamp}.
     *
     * <p>This is crucial for backward compatibility during cluster upgrades or configuration
     * changes (e.g., transitioning from precision 6 to 3). Without this relaxed check, users would
     * be unable to re-enable lake synchronization for existing tables if the cluster-wide default
     * timestamp precision has evolved.
     *
     * @param existingSchema the schema currently persisted in the Paimon catalog
     * @param newSchema the new schema descriptor generated by the current Fluss cluster
     * @return true if the physical schemas are identical, disregarding field IDs, comments, regular
     *     options, and the precision of the system timestamp
     */
    public static boolean equalIgnoreSystemColumnTimestampPrecision(
            Schema existingSchema, Schema newSchema) {
        List<DataField> existingFields = new ArrayList<>(existingSchema.fields());
        DataField systemTimestampField = existingFields.get(existingFields.size() - 1);
        if (systemTimestampField.name().equals(TIMESTAMP_COLUMN_NAME)
                && systemTimestampField
                        .type()
                        .equalsIgnoreFieldId(DataTypes.TIMESTAMP_WITH_LOCAL_TIME_ZONE())) {
            existingFields.set(
                    existingFields.size() - 1,
                    new DataField(
                            systemTimestampField.id(),
                            systemTimestampField.name(),
                            DataTypes.TIMESTAMP_LTZ_MILLIS(),
                            systemTimestampField.description()));
        }
        existingSchema = existingSchema.copy(RowType.of(existingFields.toArray(new DataField[0])));
        return equalPhysicalSchema(existingSchema, newSchema);
    }

    private static boolean equalPhysicalSchema(Schema existingSchema, Schema newSchema) {
        List<DataField> existingFields = existingSchema.fields();
        List<DataField> newFields = newSchema.fields();
        if (existingFields.size() != newFields.size()) {
            return false;
        }

        for (int i = 0; i < existingFields.size(); i++) {
            DataField existingField = existingFields.get(i);
            DataField newField = newFields.get(i);
            if (!equalDataFieldIgnoreFieldId(existingField, newField)) {
                return false;
            }
        }

        return Objects.equals(existingSchema.partitionKeys(), newSchema.partitionKeys())
                && Objects.equals(existingSchema.primaryKeys(), newSchema.primaryKeys())
                && equalPaimonOptions(existingSchema.options(), newSchema.options());
    }

    private static boolean equalPaimonOptions(
            Map<String, String> existingOptions, Map<String, String> newOptions) {
        if (!Objects.equals(
                existingOptions.get(PARTITION_GENERATE_LEGACY_NAME_OPTION_KEY),
                Boolean.FALSE.toString())) {
            return false;
        }

        for (String option : PAIMON_UNSETTABLE_OPTIONS) {
            if (!Objects.equals(existingOptions.get(option), newOptions.get(option))) {
                return false;
            }
        }

        for (String option : CoreOptions.IMMUTABLE_OPTIONS) {
            if (!Objects.equals(existingOptions.get(option), newOptions.get(option))) {
                return false;
            }
        }

        return true;
    }

    private static boolean equalDataFieldIgnoreFieldId(
            DataField existingField, DataField newField) {
        return Objects.equals(existingField.name(), newField.name())
                && existingField.type().equalsIgnoreFieldId(newField.type());
    }

    public static void checkTableIsEmpty(TablePath tablePath, FileStoreTable table) {
        if (table.latestSnapshot().isPresent()) {
            throw new TableAlreadyExistException(
                    String.format(
                            "The table %s already exists in Paimon catalog, and the table is not empty. "
                                    + "Please first drop the table in Paimon catalog or use a new table name.",
                            tablePath));
        }
    }
}
