import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'index',
    {
      type: 'category',
      label: 'Clients',
      items: [
        {type: 'autogenerated', dirName: 'user-guide'},
        {type: 'link', label: 'Java', href: 'https://fluss.apache.org/docs/0.9/apis/java-client/'},
      ],
    },
    'developer-guide/contributing',
    {
      type: 'category',
      label: 'Release',
      items: [
        {type: 'autogenerated', dirName: 'release'},
      ],
    },
  ],
};

export default sidebars;
