################################################################################
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Checks for broken links in the fluss-rust client documentation.
name: Rust Documentation Check
permissions:
  contents: read
on:
  pull_request:
    branches: [main]
    paths:
      - 'fluss-rust/website/**'
      - '.github/workflows/rust-docs-check.yml'
  push:
    branches: [main]
    paths:
      - 'fluss-rust/website/**'
      - '.github/workflows/rust-docs-check.yml'

jobs:
  check-documentation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fluss-rust/website
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Test build website
        run: npm run build -- --no-minify
